apiVersion: ''
generated: '0001-01-01T00:00:00Z'
repositories:
- caFile: ''
  certFile: ''
  insecure_skip_tls_verify: false
  keyFile: ''
  name: codedesignplus
  pass_credentials_all: false
  password: ''
  url: https://www.codedesignplus.com/helm-charts/
  username: ''